version: "3.8"
volumes:
  build_folder: null

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/frontend
    command: "yarn start"

  express:
    build:
      context: ./backend/express
      dockerfile: dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend/express:/backend
    command: "yarn start:dev"
